import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import HomeScreen from './home/Home.container';
import Navbar from 'components/base/Navbar/Navbar';

const Home: NextPage = () => {
  return (
    <div className='bg-slate-400'>
      <Navbar />
      <Head>
        <title>Angelo Umali</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <HomeScreen />
      </main>
    </div>
  );
};

export default Home;
